### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by Mastersam07** [jerolimov/flutter_alert#4]
Hi,

I'm just wondering about the status of this package. It has not been updated in a while. Is the package still maintained and accepting contributors, or if you could transfer ownership?

I will like to keep maintaining this package.

@jerolimov

**Comment by christoph-jerolimov** [comment]
Hey @Mastersam07, I'm happy to merge PRs before transferring the ownership of this project.

So if you have any recommendations how this should continue, please open some PRs.

Thanks
